name: matchr
channels:
  - defaults
dependencies:
  - asgiref=3.5.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cryptography=38.0.4
  - django=4.1
  - idna=3.4
  - libffi=3.4.2
  - openssl=1.1.1t
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-tzdata=2021.1
  - selenium=3.141.0
  - setuptools=65.6.3
  - sqlite=3.40.1
  - sqlparse=0.4.3
  - tk=8.6.12
  - tzdata=2022g
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - zlib=1.2.13
